hw11
s1ches/HT-ITIS.2.1-student pull request #11
Opened 2023-12-24 06:41 UTC by s1ches

2023-12-25 07:50 UTC, ZaripovRamil requested changes

2023-12-25 07:50 UTC, ZaripovRamil commented on Homework11/Hw11/Services/MathCalculator/IMathCalculatorService.cs
> +using Hw11.Dto;
Не нужен

2023-12-25 07:50 UTC, ZaripovRamil commented on Homework11/Hw11/Services/MathCalculator/MathCalculatorService.cs
> +using Hw11.Dto;
Тоже не нужен. Rider позволяет одним кликом почистить все в проекте
![изображение](https://github.com/s1ches/HT-ITIS.2.1-student/assets/88611748/4cd09036-5dd6-415c-915e-d2661103c76d)

2023-12-26 05:06 UTC, s1ches commented on Homework11/Hw11/Services/MathCalculator/IMathCalculatorService.cs
> +using Hw11.Dto;
Исправлено

2023-12-26 05:07 UTC, s1ches commented on Homework11/Hw11/Services/MathCalculator/MathCalculatorService.cs
> +using Hw11.Dto;
Исправлено

2023-12-26 05:58 UTC, ZaripovRamil approved these changes

2023-12-26 05:59 UTC, merged