Hw04
s1ches/HT-ITIS.2.1-student pull request #4
Opened 2023-11-27 22:42 UTC by s1ches

2023-11-29 13:49 UTC, ZaripovRamil requested changes

2023-11-29 13:49 UTC, ZaripovRamil commented on Homework4/Hw4/Program.fs
> +let args =  [| "1"; "+"; "2" |]
Сделай, чтобы аргументы с консоли приходили, как обычно

2023-11-29 13:49 UTC, ZaripovRamil commented on Homework4/Hw4/Calculator.fs
>       | Undefined = 4
CalculatorOperation используется в многих местах кода, а не только в калькуляторе, так что его лучше вынести в отдельный файл

2023-11-29 13:49 UTC, ZaripovRamil commented on Homework4/Hw4/Parser.fs
>  type CalcOptions = {
Тоже лучше вынести в отдельный файл

2023-11-29 21:29 UTC, s1ches commented on Homework4/Hw4/Program.fs
> +let args =  [| "1"; "+"; "2" |]
Исправлено

2023-11-29 21:31 UTC, s1ches commented on Homework4/Hw4/Calculator.fs
>       | Undefined = 4
Исправлено

2023-11-29 21:31 UTC, s1ches commented on Homework4/Hw4/Parser.fs
>  type CalcOptions = {
Исправлено

2023-11-30 19:17 UTC, ZaripovRamil requested changes

2023-11-30 19:17 UTC, ZaripovRamil commented on Homework4/Hw4/Program.fs
> +Array.set args 2 (Console.ReadLine())
Каждый элемент в отдельную строку - выглядит грустно, человек хочет написать "1 + 2", например, а не 3 разных ввода.

2023-12-01 07:44 UTC, s1ches commented on Homework4/Hw4/Program.fs
> +Array.set args 2 (Console.ReadLine())
Исправлено

2023-12-04 15:17 UTC, ZaripovRamil approved these changes

2023-12-04 15:18 UTC, merged