Hw05
s1ches/HT-ITIS.2.1-student pull request #5
Opened 2023-11-28 17:45 UTC by s1ches

2023-11-30 19:54 UTC, ZaripovRamil requested changes

2023-11-30 19:54 UTC, ZaripovRamil commented on Homework5/Hw5/Parser.fs
> +        let! arg2 = checkedArgs.Item3 |> tryToDouble
Тебе тут варнинги рассказывают, как это переписать хорошо

2023-12-01 08:04 UTC, s1ches commented on Homework5/Hw5/Parser.fs
> +        let! arg2 = checkedArgs.Item3 |> tryToDouble
Исправлено

2023-12-04 15:20 UTC, ZaripovRamil approved these changes

2023-12-04 15:20 UTC, merged