Hw09
s1ches/HT-ITIS.2.1-student pull request #9
Opened 2023-12-15 23:25 UTC by s1ches

Я разобрался с async lazy:))))

2023-12-20 07:55 UTC, ZaripovRamil requested changes

2023-12-20 07:55 UTC, ZaripovRamil commented on Homework9/Hw9/Extensions/EnumerableExtensions.cs
> +    }
Все использования этого расширения у тебя в коде - не тру. Используй StringSplitOptions, чтобы избавляться от пустых строк

2023-12-20 07:55 UTC, ZaripovRamil commented on Homework9/Hw9/Extensions/StringExtensions.cs
> +    public static string Without(this string value, string without) => value.Replace(without, "");
Не используются, нужно либо удалить, либо заменить использования WithoutBrackets и WithoutSpaces на Without и удалить уже WithoutBrackets и WithoutSpaces

2023-12-20 07:55 UTC, ZaripovRamil commented on Homework9/Hw9/MathExpressionHelper/ExpressionValidator.cs
> +        if (expression.WithoutSpaces().Contains("/0")) return MathErrorMessager.DivisionByZero;
Как будто на шаге валидации это все равно бессмысленно проверять, ты же все равно только один частный случай перехватываешь, а выражения вида /(5-5) все равно будут замечены только в процессе подсчетов

2023-12-20 07:55 UTC, ZaripovRamil commented on Homework9/Hw9/MathExpressionHelper/ExpressionParser.cs
> +        }
Хочется это декомпозировать в несколько методов. А если дашь этим методам говорящие названия - тебе не понадобятся отдельные комментарии в коде

2023-12-20 07:55 UTC, ZaripovRamil commented on Homework9/Hw9/MathExpressionHelper/ExpressionValidator.cs
> +        };
Зачем Task здесь?

2023-12-21 08:13 UTC, s1ches commented on Homework9/Hw9/MathExpressionHelper/ExpressionValidator.cs
> +        if (expression.WithoutSpaces().Contains("/0")) return MathErrorMessager.DivisionByZero;
Исправлено

2023-12-21 08:14 UTC, s1ches commented on Homework9/Hw9/MathExpressionHelper/ExpressionValidator.cs
> +        };
Исправлено

2023-12-21 08:17 UTC, s1ches commented on Homework9/Hw9/Extensions/StringExtensions.cs
> +    public static string Without(this string value, string without) => value.Replace(without, "");
Исправлено

2023-12-21 13:03 UTC, s1ches commented on Homework9/Hw9/Extensions/EnumerableExtensions.cs
> +    }
Исправлено

2023-12-22 12:16 UTC, ZaripovRamil commented on Homework9/Hw9/MathExpressionHelper/ExpressionParser.cs
> +        }
Обсудили, можно оставить и так. Тем более, что, кажется, сигнатуры методов в декомпозиции получатся еще страшнее и больнее, чем код с комментами

2023-12-22 12:16 UTC, ZaripovRamil approved these changes

2023-12-22 12:16 UTC, merged